import Head from "next/head";
import Button from "@mui/material/Button";
import MainLayout from "@/src/components/MainLayout";

export default function Home() {
  return (
    <MainLayout>
      <Head>
        <title>FoodPenguin - Kezdőlap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button variant="contained">Hello World</Button>

        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatibus
          ipsum nesciunt blanditiis reprehenderit consequuntur hic ad quas
          distinctio officiis, nam expedita consequatur. Quo minima, aliquam
          officiis fugiat magni quidem similique!
        </p>
      </main>
    </MainLayout>
  );
}
